### ISSUE TITLE
Bug: StackOverflowError using spyk but not spying with mockito in Robolectric

### ISSUE THREAD

**Issue by PublioDev** [mockk/mockk#41] opened 2018-03-09 21:22 UTC
Hi! First things first, thanks for the great work done.

I have a test which looks like this and it's working properly:

```kotlin
val activity = Robolectric.buildActivity(MainActivity::class.java).get()
val testActivity = Mockito.spy(activity)

testActivity.onCreate(null)

Mockito.verify(testActivity).setContentView(R.layout.activity_main)
```
How could I achieve the same with Mockk?

I have tried the following but I`m getting a StackOverflowError:

```kotlin
val activity = Robolectric.buildActivity(MainActivity::class.java).get()
val testActivity = spyk(activity)

testActivity.onCreate(null)

verify { testActivity.setContentView(R.layout.activity_main) }
```
Here the full stack trace (mockk version: 1.7.10):
https://gist.github.com/PublioDev/53c372a8fe69989a9b8f36b9b380c733

**Comment by novaterata** [comment] 2018-03-09 21:25
Are you using 1.7.10?

**Comment by oleksiyp** [comment] 2018-03-09 21:29
Thanks for reporting. Something is probably really broken. Will check it soon

**Comment by PublioDev** [comment] 2018-03-09 21:45
Sorry! I forgot to mention the version I am using. I tried both, 1.7.9 and 1.7.10

**Comment by oleksiyp** [comment] 2018-03-09 22:35
Trying to reproduce. Without success:

```
class Issue41Test {

    open class MockClsA {
        var x = 0

        open fun add() {
            x = 1
        }
    }

    open class MockClsB : MockClsA() {
        var y = 0

        override fun add() {
            y = 2
            super.add()
        }
    }

    class MockClsC : MockClsB() {
        var z = 0

        override fun add() {
            z = 3
            super.add()
        }
    }

    @Test
    fun spyStackOverflow() {
        val cls = spyk<MockClsC>()

        cls.add()

        assertEquals(1, cls.x)
        assertEquals(2, cls.y)
        assertEquals(3, cls.z)
    }
}
```

**Comment by oleksiyp** [comment] 2018-03-11 14:49
Able to reproduce in Android studio

**Comment by oleksiyp** [comment] 2018-03-11 17:30
Looks like it is quite deep interference with some Robolectric transformed code.

**Comment by PublioDev** [comment] 2018-03-12 07:17
As extra info, in my case, the error with mockk only happens if MainActivity extends AppCompatActivity but not if extends Activity. Thanks for your effort

**Comment by oleksiyp** [comment] 2019-02-13 17:10
I still not able to understand this issue. I will close it. If you still face it please report to new ticket with additional details

**Closed** 2019-02-13 17:11 UTC
Labels: bug

**Comment by SuperRabbitD** [comment] 2019-10-30 05:57
Same issue here: mockedEditText =  spyk(EditText(ApplicationProvider.getApplicationContext())) Which works fine in Mokito, but cause stackOverFlow in MockK
