### ISSUE TITLE
Bug: mocking java static method exception - o.mockk.MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString

### ISSUE THREAD

**Issue by pavelaizen** [mockk/mockk#49] opened 2018-03-21 11:29 UTC
[sample](https://gist.github.com/pavelaizen/cafc2c8c0afd7b2574fde70c3fef2f90)

running that code leads to MockKException:

objc[29348]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x1042c24c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10434e4e0). One of the two will be used. Which one is undefined.
2018-03-21 12:17:18 DEBUG - [AbstractMockFactory] Creating spyk for MyLog4jExecutor name=#1, moreInterfaces=[]
2018-03-21 12:17:18 DEBUG - [AbstractMockFactory] Creating mockk for Thread name=#2, moreInterfaces=[]
2018-03-21 12:17:19 DEBUG - [AbstractMockFactory] Creating mockk for Runnable name=#3, moreInterfaces=[]
2018-03-21 12:17:19 DEBUG - [JvmStaticMockFactory] Creating static mockk for ThreadContext
2018-03-21 12:17:19 DEBUG - [MockKProxyMaker] Injecting handler to class org.apache.logging.log4j.ThreadContext for static methods

io.mockk.MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString

at io.mockk.impl.stub.MockKStub.stdObjectAnswer(MockKStub.kt:78)

part of my dependencies:
[dependencies](https://gist.github.com/pavelaizen/22d888e1c2b4734ffa09a7b8306ebfcc)

**Comment by oleksiyp** [comment] 2018-03-21 19:27
Not able to reproduce with following code:
```
import io.mockk.*
import org.apache.logging.log4j.ThreadContext
import kotlin.test.Test

class Issue49Test {
    class MyLog4jExecutor {
        fun runBefore(t: Thread?, r: Runnable?) = ThreadContext.putAll(mutableMapOf("a" to "b"))
    }

    @Test
    fun beforeExecute() {
        val executor = spyk<MyLog4jExecutor>(recordPrivateCalls = true)
        val t = mockk<Thread>(relaxed = true)
        val r = mockk<Runnable>(relaxed = true)
        staticMockk(ThreadContext::class.java.name).use {
            executor.runBefore(t,r)
            verify { ThreadContext.putAll(any()) }
        }

    }
}
```

**Comment by oleksiyp** [comment] 2018-03-21 19:28
Need definition of `Log4jExecutor`

**Comment by pavelaizen** [comment] 2018-03-26 08:58
`
import org.apache.logging.log4j.ThreadContext
import java.util.concurrent.LinkedBlockingQueue
import java.util.concurrent.ThreadPoolExecutor
import java.util.concurrent.TimeUnit

class Log4jExecutor : ThreadPoolExecutor(1, 1,
        0L, TimeUnit.MILLISECONDS,
        LinkedBlockingQueue()) {

    override fun beforeExecute(t: Thread, r: Runnable) {
        refreshKeys()
        super.beforeExecute(t, r)
    }

    private fun refreshKeys() = ThreadContext.putAll(LogEventConstants.getThreadContextKeys())
}
`

**Comment by nieldw** [comment] 2018-11-04 13:49
I encounter the same issue with this code on version 1.8.9

```
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Logger
import org.junit.jupiter.api.Test

class LoggingTest {
 @Test
    fun `Something should be logged`() {
        mockkStatic(LogManager::class) {
            val logger = mockk<Logger>()
            every { LogManager.getLogger(any() as String) } returns logger
            // check stuff
        }
    }
}
```

**Comment by oleksiyp** [comment] 2019-02-13 17:13
@nieldw this is not totally same issue. Please open nee ticket. I reproduced only that log4j is not mockable. Closing original issue as it seems this part of code significantly changed

**Closed** 2019-02-13 17:16 UTC
Labels: bug
