### ISSUE TITLE
Formatting: [Feature request] Better error report format

### ISSUE THREAD

**Issue by Albert-Gao** [mockk/mockk#63] opened 2018-04-23 00:37 UTC
So, for a error report like this

```bash
Verification failed: call 2 of 2: class nz.salect.kotlinidiom.http.HttpKt.post(eq(http://localhost:8080/Login), eq({devid=, password=iAmNotAPassword!}), null())). Only one matching call to HttpKt(static HttpKt)/post(String, Map, Map) happened, but arguments are not matching:
[0]: argument: http://localhost:8080/Login, matcher: eq(http://localhost:8080/Login), result: +
[1]: argument: {devid=fake-dev-id, password=iAmNotAPassword!}, matcher: eq({devid=, password=iAmNotAPassword!}), result: -
[2]: argument: null, matcher: null(), result: +

Stack trace:
                                                       nz.salect.kotlinidiom.http.HttpKt.post              (http.kt:57)                               
                                                  nz.salect.kmoblib.services.AuthService.login             (AuthService.kt:40)                        
                                       nz.salect.kmoblib.AuthServiceTest$login_success$1.invoke            (AuthServiceTest.kt:165)                   
                                       nz.salect.kmoblib.AuthServiceTest$login_success$1.invoke            (AuthServiceTest.kt:17)                    
                                                       nz.salect.kmoblib.AuthServiceTest.mockHttpPost      (AuthServiceTest.kt:253)                   
                                                       nz.salect.kmoblib.AuthServiceTest.login_success     (AuthServiceTest.kt:164)                   
                                                    sun.reflect.NativeMethodAccessorImpl.invoke0           (NativeMethodAccessorImpl.java:-2)N        
                                                    sun.reflect.NativeMethodAccessorImpl.invoke            (NativeMethodAccessorImpl.java:62)         
                                                sun.reflect.DelegatingMethodAccessorImpl.invoke            (DelegatingMethodAccessorImpl.java:43)     
                                                                java.lang.reflect.Method.invoke            (Method.java:498)                          
                                               org.junit.runners.model.FrameworkMethod$1.runReflectiveCall (FrameworkMethod.java:50)                  
                                     org.junit.internal.runners.model.ReflectiveCallable.run               (ReflectiveCallable.java:12)      
```

It's detailed but still one more problem:
1. Some lines are too long such that you need horizontal scroll in order to inspect them all.

I think we can't avoid horizontal scroll in every cases, but still I think mockk can deliever a better report like this:

```bash
Verification failed: call 2 of 2: 

class nz.salect.kotlinidiom.http.HttpKt.post(). 

Only one matching call to HttpKt(static HttpKt)/post(String, Map, Map) happened, but arguments are not matching:

[0]: 2nd argument mismatch: 
    expect: {devid=fake-dev-id, password=iAmNotAPassword!}, 
    actual: {devid=, password=iAmNotAPassword!}
    
Stack trace:
nz.salect.kotlinidiom.http.HttpKt.post                      (http.kt:57)                               
nz.salect.kmoblib.services.AuthService.login                (AuthService.kt:40)                        
nz.salect.kmoblib.AuthServiceTest$login_success$1.invoke    (AuthServiceTest.kt:165)                   
nz.salect.kmoblib.AuthServiceTest$login_success$1.invoke    (AuthServiceTest.kt:17)                    
nz.salect.kmoblib.AuthServiceTest.mockHttpPost              (AuthServiceTest.kt:253)                   
nz.salect.kmoblib.AuthServiceTest.login_success             (AuthServiceTest.kt:164)   
```

**Comment by oleksiyp** [comment] 2018-06-30 17:07
What can I say? I like centered stacktraces :smile:  Not a bug, so closing

**Closed by oleksiyp** 2018-06-30 17:07 UTC
Labels: enhancement
