### ISSUE TITLE
Unexpected result unwrapping when mocking a suspending function with default arguments that returns kotlin.Result

### ISSUE THREAD

**Issue by KacperKluka** [mockk/mockk#777] opened 2022-01-03 15:59 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The mocked suspending function with default arguments returns the `Result<T>`.

### Current Behavior

The mocked function returns `T` instead of `Result<T>` and throws a `java.lang.ClassCastException`.

### Failure Information (for bugs)

The unwrapping of the `Result` only happens if we use the default arguments and omit some of them when calling the function. If we specify all the arguments when calling the function then the mock behaves correctly and returns the `Result` without unwrapping. Additionally, this only happens when the mocked function is a `suspend fun`, for regular ones it works as expected.

#### Steps to Reproduce

First, we'll need an interface with a method that is a `suspend fun` with default arguments. This method has to return a value wrapped in a `Result`, here we'll use `Result<Unit>`. Below is an interface with a method that has one required argument `name` and one optional, default argument `optionalFlag`.
```kotlin
    interface MyInterface {
        suspend fun getResult(name: String, optionalFlag: Boolean = true): Result<Unit>
    }
```

Then, we need to mock the method to always return `Result.success(Unit)`. Just in case we're mocking both versions of the method: with and without the default argument. Then we try to call the method and verify that the result matches the one we've provided to the mock.
```kotlin
    @Test
    fun shouldReturnResult() {
        runBlocking {
            // given
            val expectedResult = Result.success(Unit)
            val myInterface = mockk<MyInterface> {
                coEvery { getResult(any()) } returns expectedResult
                coEvery { getResult(any(), any()) } returns expectedResult
            }

            // when
            val result = myInterface.getResult("name")

            // then
            Assert.assertEquals(expectedResult, result)
        }
    }
```

After that instead of receiving a `Result<Unit>` from the `myInterface.getResult("name")` call we receive a `ClassCastException` because the method returns a `Unit` instead of a `Result<Unit>`.
```
java.lang.ClassCastException: class kotlin.Unit cannot be cast to class kotlin.Result (kotlin.Unit and kotlin.Result are in unnamed module of loader 'app')
```

#### Context

* MockK version: 1.12.2
* OS: Ubuntu 20.04.3 LTS
* Kotlin version: 1.5.10
* JDK version: 11.0.13
* JUnit version: 4.13.1
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation 'io.mockk:mockk:1.12.2'
    testImplementation 'junit:junit:4.13.1'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import io.mockk.coEvery
import io.mockk.mockk
import org.junit.Assert
import org.junit.Test

class MyTest {

    interface MyInterface {
        suspend fun getResult(name: String, optionalFlag: Boolean = true): Result<Unit>
    }

    @Test
    fun shouldReturnResult() {
        runBlocking {
            // given
            val expectedResult = Result.success(Unit)
            val myInterface = mockk<MyInterface> {
                coEvery { getResult(any()) } returns expectedResult
                coEvery { getResult(any(), any()) } returns expectedResult
            }

            // when
            val result = myInterface.getResult("name")

            // then
            Assert.assertEquals(expectedResult, result)
        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment] 2022-01-03 21:23
This really looks like a duplicate of #645.

**Comment by KacperKluka** [comment] 2022-01-03 21:45
It is connected to that issue for sure, but I'm not certain if those two issues are exactly the same :thinking:

**Comment by KacperKluka** [comment] 2022-04-18 17:28
FYI I've just checked and after upgrading the Kotlin version from `1.5.10` to `1.6.10` the problem is gone. So I guess that this issue can be closed :wink:

**Comment by Raibaz** [comment] 2022-04-18 20:36
Cool, thanks for sharing this!

**Closed by Raibaz** 2022-04-18 20:36 UTC

**Comment by b22n** [comment] 2022-06-10 01:29
It is still occurs in kotlin 1.6.10
