### ISSUE TITLE
match on mock argument inside verification block throws MockKException

### ISSUE THREAD

**Issue by chaosite** [mockk/mockk#282] opened 2019-04-01 15:32 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Having a `match {...}` matcher inside a verification block should work.

### Current Behavior

The test fails with a `io.mockk.MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString` exception.

#### Context

This may be user error, I'm new to MockK. I might be doing something wrong. However, the documentation suggests that this should work, and it seems pretty basic.

Google found #49, but that has to do with static methods and Java, which seems unrelated.

* MockK version: 1.9.3
* OS: MacOS X 10.14.3
* Kotlin version: 1.3.21
* JDK version: openjdk 12 2019-03-19
* JUnit version: 5.5.0-M1
* Type of test: unit test

#### Stack trace

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

io.mockk.MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString

	at io.mockk.impl.stub.MockKStub.stdObjectAnswer(MockKStub.kt:78)
	at io.mockk.impl.recording.states.SafeLoggingState.call(SafeLoggingState.kt:9)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at mocks.Thing.getId(MinimalTest.kt:6)
	at mocks.Tests$test$3$1.invoke(MinimalTest.kt:22)
	at mocks.Tests$test$3$1.invoke(MinimalTest.kt:12)
	at mocks.Tests$test$3$$special$$inlined$match$1.invoke(API.kt:668)
	at mocks.Tests$test$3$$special$$inlined$match$1.invoke(API.kt:655)
	at io.mockk.FunctionMatcher.match(Matchers.kt:58)
	at io.mockk.InvocationMatcher.match(API.kt:3777)
	at io.mockk.impl.verify.UnorderedCallVerifier.matchCall(UnorderedCallVerifier.kt:83)
	at io.mockk.impl.verify.UnorderedCallVerifier.verify(UnorderedCallVerifier.kt:33)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:31)
	at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:11)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at mocks.Tests.test(MinimalTest.kt:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:185)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:181)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:128)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

##### Dependencies
```groovy
ext.junitVersion = "5.5.0-M1"

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    testCompile "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    testCompile "org.junit.jupiter:junit-jupiter-params:$junitVersion"
    testCompile "com.natpryce:hamkrest:1.7.0.0"
    testCompile "io.kotlintest:kotlintest-assertions:3.3.1"
    runtime "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    testImplementation "io.mockk:mockk:1.9.3"
}
```
##### Reproducing example
```kotlin
package mocks

import io.mockk.*
import org.junit.jupiter.api.Test

data class Thing(val id: Int)

interface Receiver {
    fun receive(item: Thing)
}

class Tests {
    @Test
    fun test() {
        val r = mockk<Receiver>()
        val i = mockk<Thing>()
        every { i.id } returnsMany listOf(1, 2, 3)
        every { r.receive(any()) } just Runs

        r.receive(i)

        verify { r.receive(match { i.id > 0 }) }
    }
}
```

**Comment by chaosite** [comment] 2019-04-01 15:48
This seems to be related to `i` being a mock. Changing the initialization to `val i = Item(1)` makes the problem go away.

Shouldn't mocks be fine here?

**Comment by mike192** [comment] 2019-06-19 15:39
I had a similiar problem and when I removed mock this issue disappeared.

**Comment by chaosite** [comment] 2019-08-18 17:15
This is still occurring.

**Comment by fabiobauer** [comment] 2019-10-02 21:41
While verifying, MockK switches into an safe-state where the given verify-block can be evaluated safely without any modifications from the outside. 

You are using an mocked object/property in your match-block - when using/calling the property MockK's invocation-process get's triggered - BUT "you" cannot change anything while verifying, therefore you get the Exception. I think this works as intended (correct me if i'm wrong).

As mentioned by @mike192, you can solve this problem by not mocking your Thing-Class, the Object is then fully portrayed and can be used in the match-block.

Keep in mind that you shall not mock the Class your are trying to test, you want the real behavior for the Class/Object and not a simulation. Your test is pretty abstract, it'd be nice to know what your are trying to achive by it (because now you are calling an mocked function and verify it right after the call was made)

**Comment by mikeholler** [comment] 2019-10-23 22:15
I just wanted to chime in that this is also a problem for me (and regardless of whether it's the "right" thing to do, the error message could use improvement).

**Comment by fabiobauer** [comment] 2019-10-25 19:38
@mikeholler i'm totally on your side! The error message as well as the documentation should be improved.

**Comment by Raibaz** [comment] 2019-10-30 10:16
I agree that the error message here is a bit confusing, but as @fabiobauer said earlier on this thread the issue is mainly that the test here is a bit abstract. What would a good error message be in this case?

**Comment by oleksiyp** [comment] 2019-11-01 23:16
I understand that error is technical and time is wasted to understand what is happening. But it is pretty hard to improve this situation. I am closing the issue and wait till next time it appears

**Closed by oleksiyp** 2019-11-01 23:16 UTC

**Comment by mikeholler** [comment] 2019-11-02 01:12
@oleksiyp this is an unsatisfying resolution for me, and likely also for the others here. Can you provide more context as to why fixing this is untenable? Also, you say you are "wait[ing] till next time it appears", but I feel like this issue is reproducible and the reason why those who have commented on it have done so is because the error is very confusing and results in wasted effort. Could you consider also going into more detail concerning what "next time" means if it's already happened enough for us to all to find ourselves here?

Just to be clear, I'm not implying you've made a poor decision, just that I (and likely others) will read your response and potentially feel more confusion in an already confusing situation.

**Comment by oleksiyp** [comment] 2019-11-02 06:45
Ok. I will try to explain why I am closing.

1. There is no bug here. It is just thing that is not allowed to do with MockK. `verify { r.receive(match { i.id > 0 }) }`. What do you expect your logic going to do at this point? Please explain in detail, like step-by-step, because from my understanding of mocking it does not make any sense, so we need to meet at the point in the middle in our understanding.

3. Other people (@chaosite @mike192 ) don't describe details and not sure how they can reproduce your case. They can have similar error messages probably, but then they should submit it as a separate issue. I assume it won't happen at all because of pretty complex path you selected.

2. The message is a technical message, like a violation of the internals of the framework. Simply saying internal MockK error. One thing is that with sufficiently complex code you can cause internal errors in any software. And the second thing the problem is that it is hard to improve it. We can discuss more it, but first, explain what you want to achieve with code.

Thanks

**Comment by spyro2000** [comment] 2021-03-08 17:06
This also caught me today. I just wanted to verify, that the RIGHT of the mock A was passed to mock B by accessing one of it's properties.

**Comment by tricknology** [comment] 2022-06-27 17:30
For anyone else who comes across this error make sure:
1. `relaxed = true` where appropriate
2.  You're not annotating stubs with @MockK or @SpyK when they're not mocks or spies. 

Error could be more descriptive IMO
