### ISSUE TITLE
Can't seem to mock java.io.File extensions

### ISSUE THREAD

**Issue by ProjectMoon** [mockk/mockk#90] opened 2018-06-14 11:11 UTC
I'm trying to mock the endsWith method on Kotlin's java.io.File extensions in a JUnit Test:

```kotlin
mockkStatic("kotlin.io.FilesKt")
val file: File = mockk()
every { file.endsWith(any<String>()) } returns true
```

This fails with the following error, as if the extensions class was not instrumented for static method interception. Basically it appears to actually be calling the extension method, which of course fails due to it being a mock.

```
io.mockk.MockKException: Failed matching mocking signature for
File(#3).getPath()
left matchers: [any()]

	at io.mockk.impl.recording.ChainedCallDetector$detect$8.invoke(ChainedCallDetector.kt:146)
	at io.mockk.impl.recording.ChainedCallDetector.detect(ChainedCallDetector.kt:170)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:29)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
```

The `endsWith` function is defined in Kotlin's internal file kotlin.io.Utils.kt, with these annotations at the top:

```kotlin
@file:JvmVersion
@file:JvmMultifileClass
@file:JvmName("FilesKt")
package kotlin.io
```

I tried reproducing this with my own set of extension functions and objects that match the problem as closely as possible, but those worked just fine. What am I doing wrong here? Or did I find a bug?

**Comment by oleksiyp** [comment] 2018-06-14 11:48
Thanks for reporting. Will check as soon as get near by computer

**Comment by Kerooker** [comment] 2018-06-14 12:10
I also failed to reproduce this using my own files:

TestFile.kt
```
@Test
    fun `test`() {
        mockkStatic("foo.FooKt")
        val file: File = mockk()
    
        every { file.foo() } returns "X"
        
        Assert.assertEquals(file.foo(), "X")
    }
```

File TestUtils.kt

```
@file:JvmMultifileClass
@file:JvmName("FooKt")
package foo

import java.io.File

public fun File.foo(): String {
    return "bar"
}
```

When debugging, the original code is executed


[Reference to Utils.kt where extension functions are located](https://github.com/JetBrains/kotlin/blob/691737dbf07cd47fd65f1ac6b7912907854fec48/libraries/stdlib/jvm/src/kotlin/io/files/Utils.kt#L373)

**Comment by oleksiyp** [comment] 2018-06-14 15:49
It is not reproducible for me.
Please make sure you use latest version "io.mockk:mockk:1.8.3"

As well you don't need to mock twice. 
Static mockk is enough to mock `foo` function because it is top-level extension function.
Imagine receiver(that thing before dot) is just passed as a parameter to `foo`.
```
        mockkStatic("foo.FooKt")
        every { any<File>().foo() } returns "X"
        println(File("abc").foo())
```

**Comment by Kerooker** [comment] 2018-06-14 15:56
@oleksiyp Are you able to execute the original code correctly? The error seems to not be reproducible for my comment, but I also had an error with the original problem

**Comment by oleksiyp** [comment] 2018-06-14 16:07
Ok, I know what the problem. Useful in this situation is `Tools -> Kotlin -> Show Kotlin Bytecode`. Here I can see that actual name of a class is different.

Here is working example:
```
        mockkStatic("kotlin.io.FilesKt__UtilsKt")
        every { File("abc").endsWith(any<String>()) } returns true
        println(File("abc").endsWith("abc"))
```

**Comment by Kerooker** [comment] 2018-06-14 16:19
This is an odd behaviour. Should this "Guide" of your be added to the documentation in any forms?

**Comment by Kerooker** [comment] 2018-06-14 16:27
@oleksiyp 
I think the code is generated this way because there are some inner classes: OnErrorAction, TerminateException.

If I modify my class to 
```
@file:JvmMultifileClass
@file:JvmName("FooKt")
package foo

import java.io.File

public fun File.foo(): String {
    return "bar"
}

enum class Fooer {
    FOO, BAR
}
```

My original test will fail.

I have to modify it to 
```
@Test
    fun `test test`() {
        mockkStatic("foo.FooKt__TestUtilsKt")

        every { File("a").foo() } returns "X"

        Assert.assertEquals("X", File("a").foo())
    }

```

**Comment by oleksiyp** [comment] 2018-06-15 20:53
Added to docs. https://github.com/mockk/mockk/blob/master/README.md#extension-functions 

Closing ticket

**Closed by oleksiyp** 2018-06-15 20:53 UTC
Labels: help wanted
