### ISSUE TITLE
Add toggle for stack traces from verify

### ISSUE THREAD

**Issue by kkurczewski** [mockk/mockk#427] opened 2020-04-09 13:00 UTC
In #19 there was added feature to show stack trace when `verify` expectation failed. 

I don't find this stack trace useful **most of the time**. More often I'm rather interested **what** exactly failed and long stack trace on bottom forces me to scrolling up for actual root cause.

Can we make some toggle for this feature? I would prefer to manually switching this on.

Naive solution:
`verify(printStackTrace = true) { ... }`

**Comment by oleksiyp** [comment] 2020-04-19 09:15
Created special settings flag: https://github.com/mockk/mockk/blob/develop/README.md#settings-file

Committed to develop branch

**Comment by kkurczewski** [comment] 2020-04-19 14:44
Cool to see, thanks :)

**Comment by pusolito** [comment] 2020-04-21 03:28
This doesn't seem to work for me.  I've tried flipping the config back and forth with same result: long stack traces when verification fails.  I've also confirmed that other settings (i.e. relaxed) work.  Flipping it to false makes tests that assumed relaxed mocks fail.  What am I missing?

here's my settings file:

```properties
resources/io/mock/settings.properties
--------------------------------------

relaxed=true
relaxUnitFun=true
#recordPrivateCalls=false
stackTracesOnVerify=false
```

**Comment by olbpetersson** [comment] 2020-04-21 15:58
@oleksiyp is there anyway to do this programmatically if you'd like to avoid having a settings-file? Didn't find anything in the code base or the source code when jumping in via intellij

**Comment by olbpetersson** [comment] 2020-04-22 10:03
@oleksiyp is there anyway to do this programmatically if you'd like to avoid having a settings-file? Didn't find anything in the code base or the source code when jumping in via intellij

**Comment by oleksiyp** [comment] 2020-04-22 11:23
No way currently only. Only settings file

**Comment by guilherme-pereira-ifood** [comment] 2020-08-18 20:46
`stackTracesOnVerify=false` on `settings.properties` not working for me too. We're suffering with big logs when tests fails, is there any workaround for this?

**Comment by Raibaz** [comment] 2021-03-11 22:54
Need to check this again.

**Comment by kkurczewski** [comment] 2021-10-15 14:08
I could take a look on this if someone could provide me instruction how build jar and release it to local repository. I tried just running:
```
./gradlew build
```
But it fails on missing dependency:
```
* What went wrong:
Could not determine the dependencies of task ':mockk-agent-api:dokkaJavadoc'.
> Could not resolve all task dependencies for configuration ':mockk-agent-api:dokkaJavadocPlugin'.
   > Could not find com.soywiz.korlibs.korte:korte-jvm:1.10.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/soywiz/korlibs/korte/korte-jvm/1.10.3/korte-jvm-1.10.3.pom
       - https://dl.google.com/dl/android/maven2/com/soywiz/korlibs/korte/korte-jvm/1.10.3/korte-jvm-1.10.3.pom
     Required by:
         project :mockk-agent-api > org.jetbrains.dokka:javadoc-plugin:1.4.20
   > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
     Required by:
         project :mockk-agent-api > org.jetbrains.dokka:javadoc-plugin:1.4.20
         project :mockk-agent-api > org.jetbrains.dokka:javadoc-plugin:1.4.20 > org.jetbrains.dokka:dokka-base:1.4.20
```

So, if someone could tell me how I can create local artifact from code then I can take a look what's going on under hood.

**Comment by Raibaz** [comment] 2021-10-15 20:46
To get the build to pass with a freshly-cloned repo I think you can just skip the dokka Javadoc generation by doing

```
./gradlew build -x dokkaJavadoc
```

It shouldn't be a big deal not to have dokka generating the docs on your machine :)

**Comment by kkurczewski** [comment] 2021-10-16 10:45
I have to comment out some stuff and exclude dokka plugin in order to build artifact. Anyway, root cause was that not every path that printed stack trace was covered with flag check, PR above should fix issue.

**Comment by piotrb5e3** [comment] 2022-10-14 08:25
Can this issue be closed? Was it resolved?

**Comment by Raibaz** [comment] 2022-10-14 08:33
Yes, thanks.

**Closed by Raibaz** 2022-10-14 08:33 UTC
Labels: enhancement, important, good-first-issue, good first issue, hacktoberfest

**Comment by Zordid** [comment] 2025-02-05 06:13
> This doesn't seem to work for me. I've tried flipping the config back and forth with same result: long stack traces when verification fails. I've also confirmed that other settings (i.e. relaxed) work. Flipping it to false makes tests that assumed relaxed mocks fail. What am I missing?
> 
> here's my settings file:
> 
> resources/io/mock/settings.properties
> --------------------------------------

You are using the wrong path, which because of your comment here also lead me to copy and paste. :(

The correct path is, of course, `io/mockk`, not mock!
