### ISSUE TITLE
Cannot mock object properties with initializer

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#202] opened 2018-12-18 16:16 UTC
<details>

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

</details>

### Expected Behavior

I can mock object properties with initializers.

### Current Behavior

I can't mock object properties with initializers. Instead, I have to give the property a backing field and use the `get()` getter to  be able to mock it.

### Failure Information (for bugs)

The object's initialized property isn't mocked. The initialized value is used instead. It seems that using an initializer instead of a getter hard-sets the properties' value and that it can't be mocked by mocking the getter. Looking at the Java bytecode I can't see significant differences between a property with a getter with a backing property, or just a property with an initializer. It seems MockK can't mock an object's property with initializer using `mockObject`. Am I using the wrong mocking method?

With my current approach, I have to use a backing field to create a mockable getter. This is a code smell, because now my code is adapted to be testable with MockK.

#### Steps to Reproduce

1. Run the example code in this issue.
1. Note that one of two methods succeeds.
1. Check out stacktrace of failed method.
1. Wonder why.

#### Context

* MockK version: 1.8.13.kotlin13
* OS: macOS 10.14.2 (18C54)
* Kotlin version: 1.3.11
* JDK version:
```
$ '/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java' -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
OpenJDK 64-Bit Server VM (build 25.152-b06, mixed mode)
```

* JUnit version: 4.12
* Type of test: unit test ~OR android instrumented test~

#### Stack trace

```
java.lang.AssertionError: Verification failed: call 1 of 1: Z(#1).funny()) was not called

	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:63)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:41)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
	at io.mockk.MockKDsl.internalVerify(API.kt:119)
	at io.mockk.MockKKt.verify(MockK.kt:139)
	at io.mockk.MockKKt.verify$default(MockK.kt:136)
	at com.example.InitializerTest.Y_print() calls Y_z_funny()(InitializerTest.kt:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:28.0.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    def coroutines_version = '1.0.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version"

    def junit_vintage_version = "4.12"
    testImplementation "junit:junit:$junit_vintage_version"

    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    def moshi_version = "1.8.0"
    implementation "com.squareup.moshi:moshi:$moshi_version"
    implementation "com.squareup.moshi:moshi-adapters:$moshi_version"
    kapt "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"

    def retrofit_version = '2.5.0'
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofit_version"
    implementation 'ru.gildor.coroutines:kotlin-coroutines-retrofit:0.13.0-eap13'

    def mockk_version = '1.8.13.kotlin13'
    testImplementation "io.mockk:mockk:$mockk_version"

    def robolectric_version = "4.1"
    testImplementation "org.robolectric:robolectric:$robolectric_version"
    testImplementation "org.robolectric:shadows-supportv4:$robolectric_version"
}

// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.example

import io.mockk.*
import org.junit.After
import org.junit.AfterClass
import org.junit.BeforeClass
import org.junit.Test

class InitializerTest {
    companion object {
        private val zMock = mockk<Z>(relaxed = true)

        @BeforeClass
        @JvmStatic
        fun `before class`() {
            mockkObject(X)
            mockkObject(Y)
        }

        @AfterClass
        @JvmStatic
        fun `after class`() = unmockkAll()
    }

    @After
    fun after() = clearAllMocks()

    @Test
    fun `X_print() calls X_z_funny()`() {
        every { X.z } returns zMock

        X.funny()

        verify { zMock.funny() }
    }

    @Test
    fun `Y_print() calls Y_z_funny()`() {
        every { Y.z } returns zMock

        Y.funny()

        verify { zMock.funny() }
    }
}

object X {
    val z get() = z_
    private val z_ = Z()
    fun funny() = z.funny()
}

object Y {
    val z = Z()
    fun funny() = z.funny()
}

class Z {
    fun funny() = ""
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment] 2018-12-20 01:49
Thanks for report. It is weird indeed

**Comment by oleksiyp** [comment] 2018-12-20 01:58
I think the problem is that Kotlin using optimization to access the field:
```
package abc;

import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {1, 1, 13},
   bv = {1, 0, 3},
   k = 1,
   d1 = {"\u0000\u001a\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u000e\n\u0000\bÆ\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J\u0006\u0010\u0007\u001a\u00020\bR\u0011\u0010\u0003\u001a\u00020\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u0005\u0010\u0006¨\u0006\t"},
   d2 = {"Labc/Y;", "", "()V", "z", "Labc/Z;", "getZ", "()Labc/Z;", "funny", "", "playground-kt13"}
)
public final class Y {
   @NotNull
   private static final Z z;
   public static final Y INSTANCE;

   @NotNull
   public final Z getZ() {
      return z;
   }

   @NotNull
   public final String funny() {
      return z.funny();
   }

   static {
      Y var0 = new Y();
      INSTANCE = var0;
      z = new Z();
   }
}
```

**Comment by oleksiyp** [comment] 2018-12-20 01:59
Here you can see direct backing field access:
```
   @NotNull
   public final String funny() {
      return z.funny();
   }
```

**Comment by oleksiyp** [comment] 2018-12-20 02:00
To handle such case quite significant bytecode transformation is needed. (replace all backing field accesses)

**Comment by erikhuizinga** [comment] 2018-12-20 08:23
Thanks for looking into this. Since there is a (flawed) solution (use backing fields instead of direct access), this issue doesn't have high priority. However, this would be a very good feature for a Kotlin mocking library.

It might be worth to take a look at other mocking libraries and if they can mock directly initialized properties. And how they do it.

**Comment by oleksiyp** [comment] 2018-12-25 07:07
Related #104 . Closing

**Closed by oleksiyp** 2018-12-25 07:07 UTC
