### ISSUE TITLE
Mocking Extension function only works for data class

### ISSUE THREAD

**Issue by martofeld** [mockk/mockk#504] opened 2020-10-07 17:02 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

When mocking extension functions for a class I expect the function to be mocked

### Current Behavior

When mocking extension functions for a class I get an exception

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Copy test from https://mockk.io/#extension-functions
2. Run test and see it pass
3. Change `data class Obj` to `class Obj`
4. Test now fails with the exception below

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: MacOS Catalina
* Kotlin version: 1.3.72
* JDK version: 1.8
* JUnit version: 4.13
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: no answer found for: Ext(#3).extensionFunc(com.**.**.Obj@20834b01)
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at com.**.**.Ext.extensionFunc(ApiTest.kt:117)
	at com.**.**.Test.test(ApiTest.kt:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```gradle
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
```

### This test works (straight out of the docs)
```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.**.**

import io.mockk.mockk

data class Obj(val value: Int)

class Ext {
    fun Obj.extensionFunc() = value + 5
}

class Test {
    @Test
    fun test() {
        with(mockk<Ext>()) {
            every { Obj(5).extensionFunc() } returns 11
            assertEquals(11, Obj(5).extensionFunc())
            verify { Obj(5).extensionFunc() }
        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

### This test fails, note that the only difference is that `Obj` is not a data class anymore
```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.**.**

import io.mockk.mockk

class Obj(val value: Int)

class Ext {
    fun Obj.extensionFunc() = value + 5
}

class Test {
    @Test
    fun test() {
        with(mockk<Ext>()) {
            every { Obj(5).extensionFunc() } returns 11
            assertEquals(11, Obj(5).extensionFunc())
            verify { Obj(5).extensionFunc() }
        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Neuman968** [comment] 2021-03-08 01:07
Hello! I have been using and following this project for a long time and was going to take a stab at trying to solve this issue. 

However when running the tests I am not entirely sure that there is any bug causing this. Data classes give you equals and hash code implementations by default whereas classes you have to implement them yourself if you want equality to work. 

If you modify the failing test provided to give Obj an equals implementation the tests pass. 

```kotlin
import io.mockk.*
import io.mockk.verify
import kotlin.test.Test
import kotlin.test.assertEquals

class Obj(val value: Int) {
    override fun equals(other: Any?): Boolean {
        return when (other) {
            is Obj -> other.value == this.value
            else -> false
        }
    }

}

class Ext {
    fun Obj.extensionFunc() = value + 5
}

class Issue504Test {
    @Test
    fun test() {
        with(mockk<Ext>()) {
            every { Obj(5).extensionFunc() } returns 11
            assertEquals(11, Obj(5).extensionFunc())
            verify { Obj(5).extensionFunc() }
        }
    }
}
```

Also, if you change the test to use a single instance of `Obj(5)` the test also passes. 

```kotlin
import io.mockk.*
import io.mockk.verify
import kotlin.test.Test
import kotlin.test.assertEquals

class Obj(val value: Int)

class Ext {
    fun Obj.extensionFunc() = value + 5
}

class Issue504Test {
    @Test
    fun test() {
        val obj = Obj(5)
        with(mockk<Ext>()) {
            every { obj.extensionFunc() } returns 11
            assertEquals(11, obj.extensionFunc())
            verify { obj.extensionFunc() }
        }
    }
}
```

I am not sure that this is a defect with mockk, but maybe some confusion from the documentation. Let me know if there is anything I can do to help. Maybe we can add this to a common gotchas section of the documentation or something. 

Thank you for your time!

**Comment by Raibaz** [comment] 2021-03-08 21:55
Thanks a lot for investigating this!

I think it makes sense that having the equals method defined makes a difference in this case: method handlers are stored in a map, which is the reason why matching an `every` block to a `verify` block only works if the mocked object has an equals function, or if they are the same object reference.

I may actually take a shot at fixing this tomorrow, as I have been hitting a bug on constructor mocking that is likely caused by the same reason, so it may be the case that your investigation killed two birds with one stone :)

Thanks again!

**Comment by Neuman968** [comment] 2021-03-08 22:32
My pleasure, 

The place where this test fails is in file API.kt method `fun match(invocation: Invocation): Boolean`

In cases where equals is not implemented, the check on line 3742 fails

```kotlin
    if (!matcher.match(arg)) {
        return false
    }
```

In the above cases matcher is an EqMatcher.  Hope this helps you some more. Thanks!

**Comment by maxidelo** [comment] 2021-11-22 10:48
Hi there,

I'm having the same issue, updated to version `1.12.1` but still no luck. 
Is there any update on this ?

Thanks

**Comment by affishaikh** [comment] 2022-02-16 03:36
I am getting a different error. I have the same class

`class Obj(val value: Int)`

and have the same extension function. But the extension is not put in a class.

`fun Obj.extensionFunc() = value + 5`

When I am trying to mockk the extension function like this:

`@Test
    fun mocking() {
        val objMock = mockk<Obj>()

        every {
            Obj(5).extensionFunc()
        } returns 11

        Obj(5).extensionFunc() shouldBe 11
    }`
    
    I get below error:
    
    
   

> Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)

**Comment by jknair0** [comment] 2022-03-31 02:42
@affishaikh, like @Neuman968 has suggested this is the issue of creating different object references. one that you are mocking in `every` block the other you are asserting on.

Both might look similar but will not be same unless you provide `equals`

instead you can create a same object the test would pass without problem.

```kotlin
val sameObject = Obj(5)
 every {
        // this object is being mocked 
        sameObject.extensionFunc()
} returns 11

// the same object you are asserting on.
sameObject.extensionFunc() shouldBe 11
```

**Comment by OitoH** [comment] 2023-10-06 00:06
I took a look at this as my "first issue"

After reproducing the issue I got the following error message:

> no answer found for ClassWithoutToEqualsExt(#1).plusFive(io.mockk.it.ClassWithoutToEquals@6a89aa01) among the configured answers: (ClassWithoutToEqualsExt(#1).plusFive(eq(io.mockk.it.ClassWithoutToEquals@a5d2ebe))))
io.mockk.MockKException: no answer found for ClassWithoutToEqualsExt(#1).plusFive(io.mockk.it.ClassWithoutToEquals@6a89aa01) among the configured answers: (ClassWithoutToEqualsExt(#1).plusFive(eq(io.mockk.it.ClassWithoutToEquals@a5d2ebe))))
	at app//io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:91)

Based on the message it seems clear to me that io.mockk.it.ClassWithoutToEquals@6a89aa01 and io.mockk.it.ClassWithoutToEquals@a5d2ebe are not equal, leading to no answer being found.

Since the objects are indeed not equal, I believe the library is not misbehaving and that this is **not a bug**, the previous log message just didn't make it clear why no answer matched.

The improved error log message was introduced by https://github.com/mockk/mockk/commit/e18cae7a12fc693be9eb74fa84d1fcb64031aa31

Which I believe that should be regarded as the commit that fixed this issue.

@Raibaz do you think this issue should be closed based on this analysis ?

**Comment by Raibaz** [comment] 2023-12-17 21:56
Thanks for the investigation, makes sense to me to close this.

**Closed by Raibaz** 2023-12-17 21:56 UTC
Labels: bug, important, good-first-issue, good first issue, hacktoberfest
